### PR TITLE
Upgrade to NJsonSchema in version 11.0.0

### LINKED ISSUE #179: Nswag 14 MapAsyncApiDocuments failing
When using Saunter (0.12.0) along with NSwag version 14.0.0, the method MapAsyncApiDocuments is broken with MissingMethodException. The latest version of NJsonSchema removed the public void constructor for the JsonSchemaGeneratorSettings file:

https://github.com/RicoSuter/NJsonSchema/blob/41443e7f48cb231f5dd728662924b706d6d99a39/src/NJsonSchema/Generation/JsonSchemaGeneratorSettings.cs

image

### PR DESCRIPTION
**Pull request by zarusz**
* Fixes #179 
* Upgrade to NJsonSchema in version 11.0.0, which decoupled NewtonsoftJson into related NJsonSchema.NewtonsoftJson dependency

Signed-off-by: Tomasz Maruszak <maruszaktomasz@gmail.com>

### CODE REVIEW

**Comment by zarusz** [comment]
Hey @m-wild, would it be possible to incorporate this PR and release a new version?

Right now we are blocked from moving to the latest NET8 + NSwag toolchain.

Not sure where this project is going, but I saw some forks, and an announcement that you are looking for maintainers.

Interested to hear what to do next here.

**Comment by m-wild** [comment]
I'll get it merged and released in the next 48hrs.

**Review by m-wild — APPROVED** [review]

**Comment by m-wild** [comment]
Released as v0.13.0 https://www.nuget.org/packages/Saunter/0.13.0

**Comment by zarusz** [comment]
Appreciate the help and fast response on this!

**Pull request merged**
